### ISSUE TITLE
Images not shown

### ISSUE THREAD

**Issue by polfernandez** [ionicthemes/ionic3-wordpress-integration#11]
The images of the posts do not appear.

**Comment by djabif** [comment]
Can you please include more information about this issue?

**Comment by polfernandez** [comment]
The images inserted on the posts are not shown in the ionic app. p.e if you load the wordpress: www.cordill.cat, the images/media on the posts are not present

**Comment by djabif** [comment]
Please note that we only display [the post excerpt](https://github.com/ionicthemes/ionic3-wordpress-integration/blob/master/src/pages/home/home.ts#L49)
You can change this in order to display the full post in your ionic app if you need. Check the wordpress API for reference https://developer.wordpress.org/rest-api/reference/posts/
